namespace: community
name: lbry
version: 0.1.0
readme: README.md
authors:
  - Rhys Campbell (github.com/rhysmeister)
description: Contains modules for working with the LBRY digital-content blockchain platform. Find out more at [lbry.tech](https://lbry.tech/).
license_file: LICENSE
tags:
  - lbry
  - blockchain
  - crypto
  - content
repository: https://github.com/ansible-collections/community.lbry
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/ansible-collections/community.lbry
issues: https://github.com/ansible-collections/community.lbry/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
