---
# setup docker for the LBRY Pi System
- name: Install docker
  block:

    - name: Install with get-docker.sh
      script:
        cmd: get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Ensure the lbry user can use docker
      user:
        name: "{{ lbry_user }}"
        groups: docker
        append: yes

- name: Start docker containers
  block:

      - name: Create lbry network for docker
        docker_network:
          name: lbry

      - name: Start an elastic server in a container
        docker_container:
          name: es01
          image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
          env:
            "node.name": "es01"
            "discovery.type": "single-node"
            "indices.query.bool.max_clause_count": "8192"
            "bootstrap.memory_lock": "true"
            "ES_JAVA_OPTS": "-Xms1g -Xmx1g"
          ulimits: 
            - memlock:-1:-1
          ports:
            - 127.0.0.1:9200:9200
          volumes:
            - es01:/usr/share/elasticsearch/data
          networks:
            - name: "lbry"
        retries: 3
        register: elastic

      - name: Wait for the elastic container to become active
        wait_for:
          port: 9200
          delay: 30
        when: elastic.changed

      - name: Start a wallet server in a container
        docker_container:
          name: walletserver
          image: lbry/wallet-server:latest-release
          ports:
            - "127.0.0.1:50001:50001/tcp" # rpc port
            - "127.0.0.1:2112:2112"
          env:
            "DB_DIRECTORY": "/database"
            "DAEMON_URL": "http://lbry:lbry@172.17.0.1:29245"  # host ip of the docker host on default network
            "MAX_QUERY_WORKERS": "4"
            "CACHE_MB": "1024"
            "MAX_SEND": "1000000000000000000"
            "MAX_RECEIVE1": "000000000000000000"
            "MAX_SESSIONS": "100000"
            "HOST": "0.0.0.0"
            "TCP_PORT": "50001"
            "PROMETHEUS_PORT": "2112"
            "FILTERING_CHANNEL_IDS": "770bd7ecba84fd2f7607fb15aedd2b172c2e153f 95e5db68a3101df19763f3a5182e4b12ba393ee8"
            "BLOCKING_CHANNEL_IDS": "dd687b357950f6f271999971f43c785e8067c3a9 06871aa438032244202840ec59a469b303257cad b4a2528f436eca1bf3bf3e10ff3f98c57bd6c4c6"
            "ELASTIC_PORT": "9200"
            "ELASTIC_HOST": "es01"
            "ALLOW_LAN_UDP": "True"
            "ALLOW_LOCALHOST": " True"
            "NET": "regtest"
          volumes:
            - "wallet_server:/database"
          networks:
            - name: "lbry"
        retries: 3
        register: walletserver

      